on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json

  inno-compile:
    runs-on: windows-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
        - uses: actions/checkout@v4

        - name: download godot-mod-loader from catbox
          shell: pwsh
          run: |
            Invoke-WebRequest -Uri https://files.catbox.moe/i0kfcm.zip -OutFile "godot-mod-loader.zip"
            Expand-Archive -Path ".\godot-mod-loader.zip" -DestinationPath ".\godot-mod-loader" -Force

        - uses: Minionguyjpro/Inno-Setup-Action@v1.2.9
          with:
            path: GMLInstaller.iss

        - uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ needs.release-please.outputs.tag_name }}
            files: Output/*.exe